### ISSUE TITLE
Support for building against system libyaml

### ISSUE THREAD

**Issue by craigbarnes** [acd/lua-yaml#2]
Hi. I [forked](https://github.com/craigbarnes/lua-yaml) this repository a while back because I thought it was an unmaintained import from LuaForge but I've just noticed the recent activity. I originally intended to maintain the code but all I've actually done since is remove the bundled libyaml files, update the [Makefile](https://github.com/craigbarnes/lua-yaml/blob/master/Makefile) to build against the system's libyaml package and a few other minor tweaks.

Would you be interested in merging the changes I made to the Makefile, to make it easier to package lua-yaml for Linux distros? It would still be possible to keep the bundled libyaml (if required for convenience or building on Windows etc.), by moving it into a subdirectory and building with, for example, `make local`:

```
local:
        $(MAKE) XCFLAGS="-I./libyaml" LDLIBS="-L./libyaml -lyaml"
```

**Comment by linuxmaniac** [comment]
Hi,
craigbarnes your repo[0] vanished have you got this changes?

[0] https://github.com/craigbarnes/lua-yaml

**Comment by craigbarnes** [comment]
I still have a private copy of the repo, but I removed it from GitHub to avoid giving the impression that I'm willing to become de facto maintainer. There's another fork [here](https://github.com/gvvaughan/lyaml), which incorporates most of the same changes I made, and seems to be actively maintained.

**Comment by linuxmaniac** [comment]
I will go for lyaml, Thanks!
